[2025-07-06T20:45:08.969+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-06T20:45:08.989+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_datos_potencia.ETL.cargar_demandas_mensuales manual__2025-07-06T20:45:01.507636+00:00 [queued]>
[2025-07-06T20:45:08.996+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_datos_potencia.ETL.cargar_demandas_mensuales manual__2025-07-06T20:45:01.507636+00:00 [queued]>
[2025-07-06T20:45:08.997+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-06T20:45:09.011+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ETL.cargar_demandas_mensuales> on 2025-07-06 20:45:01.507636+00:00
[2025-07-06T20:45:09.021+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=569) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-06T20:45:09.023+0000] {standard_task_runner.py:72} INFO - Started process 574 to run task
[2025-07-06T20:45:09.023+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag_datos_potencia', 'ETL.cargar_demandas_mensuales', 'manual__2025-07-06T20:45:01.507636+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/potencia_etl_dag.py', '--cfg-path', '/tmp/tmpqs24vr2w']
[2025-07-06T20:45:09.025+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask ETL.cargar_demandas_mensuales
[2025-07-06T20:45:09.081+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_datos_potencia.ETL.cargar_demandas_mensuales manual__2025-07-06T20:45:01.507636+00:00 [running]> on host b7670b46f5dc
[2025-07-06T20:45:09.157+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag_datos_potencia' AIRFLOW_CTX_TASK_ID='ETL.cargar_demandas_mensuales' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T20:45:01.507636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T20:45:01.507636+00:00'
[2025-07-06T20:45:09.159+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-06T20:45:13.200+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-06T20:45:13.209+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-06T20:45:13.210+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_dag_datos_potencia, task_id=ETL.cargar_demandas_mensuales, run_id=manual__2025-07-06T20:45:01.507636+00:00, execution_date=20250706T204501, start_date=20250706T204508, end_date=20250706T204513
[2025-07-06T20:45:13.249+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-06T20:45:13.266+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T20:45:13.268+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
